golf/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'hello#home'
  get 'cake', to: 'hello#cake'

  resources :articles
end

golf/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

golf/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

golf/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

golf/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was successfully saved"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	private
		def article_params
			params.require(:article).permit(:title, :description)
		end
end

golf/app/controllers/hello_controller.rb
class HelloController < ApplicationController

def home

end

def cake

end

end

golf/app/helpers/application_helper.rb
module ApplicationHelper
end

golf/app/views/articles/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Create new article</title>
</head>

<body>

	<h1>Create an article</h1>

	<% if @article.errors.any? %>
		<h3>The following messages occurred: </h3>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>	
		</ul>
	<% end %>

	  <!-- Create a form for our new article -->
		<%= form_for @article do |f| %>
			<p>
				<%= f.label :title %><br/>
				<%= f.text_field :title %>
			</p>

			<p>
				<%= f.label :description %><br/>
				<%= f.text_area :description %>
			</p>

			<p>
				<%= f.submit %>
			</p>
		<% end %>

	</body>
</html>

golf/app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h1>Showing selected article</h1>
	<p> Title: <%= @article.title %></p>
	<p> Description: <%= @article.description %></p>
	
</body>
</html>

golf/app/views/hello/cake.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CAKE</title>
	</head>

	<h1>This is le cake page!</h1>
	<body>
	<%= link_to 'Home', root_path %>
	</body>
</html>

golf/app/views/hello/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
</head>

<h1>THIS IS THE HOME!!</h1>
<body>
<%= link_to 'Cake', cake_path %>
</body>
</html>

golf/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- Whenever we get a flash message, display all of them -->
  	<% flash.each do |name, msg| %>
  		<ul>
  			<li> <%= msg %> </li>
  		</ul>
  	<% end %>
    <%= yield %>
  </body>
</html>